import { ReportBrandHeader } from './ReportBrandHeader';
import type { CompanyBrand } from '../../api/reports';

export interface ReceiptPreviewPdfProps {
  brand: CompanyBrand;
  heading: string;
  partyName: string;
  amount: number;
  dateTime: string;
  fromAccountName?: string | null;
  toAccountName?: string | null;
  referenceNumber?: string | null;
  method?: string | null;
  notes?: string | null;
  branchName?: string | null;
  referenceType?: string | null;
  generatedBy: string;
}

const fmt = (n: number): string =>
  n.toLocaleString('en-PK', { maximumFractionDigits: 2, minimumFractionDigits: 2 });

const formatDateTime = (iso: string): string => {
  if (!iso) return '';
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return `${d.toLocaleDateString('en-PK', { day: '2-digit', month: 'short', year: 'numeric' })} · ${d.toLocaleTimeString('en-PK', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  })}`;
};

/** Payment-receipt style page intended for PdfPreviewModal. */
export function ReceiptPreviewPdf({
  brand,
  heading,
  partyName,
  amount,
  dateTime,
  fromAccountName,
  toAccountName,
  referenceNumber,
  method,
  notes,
  branchName,
  referenceType,
  generatedBy,
}: ReceiptPreviewPdfProps) {
  const rows: Array<[string, string]> = [];
  if (referenceNumber) rows.push(['Reference #', referenceNumber]);
  if (referenceType) rows.push(['Type', referenceType.replace('_', ' ')]);
  if (method) rows.push(['Method', method]);
  if (branchName) rows.push(['Branch', branchName]);
  if (fromAccountName) rows.push(['From', fromAccountName]);
  if (toAccountName) rows.push(['To', toAccountName]);
  rows.push(['Date & Time', formatDateTime(dateTime)]);

  return (
    <div>
      <ReportBrandHeader brand={brand} title={heading} subtitle={partyName} />

      <div
        style={{
          border: '2px solid #111827',
          padding: 18,
          borderRadius: 6,
          marginBottom: 18,
          textAlign: 'center',
          background: '#f9fafb',
        }}
      >
        <div style={{ fontSize: 10, textTransform: 'uppercase', letterSpacing: 1, color: '#555' }}>Amount</div>
        <div style={{ fontSize: 30, fontWeight: 800, marginTop: 4 }}>Rs. {fmt(amount)}</div>
      </div>

      <table style={{ marginBottom: 14 }}>
        <tbody>
          {rows.map(([k, v]) => (
            <tr key={k}>
              <td style={{ width: 130, color: '#555' }}>{k}</td>
              <td style={{ fontWeight: 600 }}>{v}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {notes && (
        <div style={{ marginBottom: 14, padding: 10, border: '1px solid #e5e7eb', borderRadius: 4 }}>
          <div style={{ fontSize: 10, color: '#555', marginBottom: 4 }}>Notes</div>
          <div style={{ whiteSpace: 'pre-line' }}>{notes}</div>
        </div>
      )}

      <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 10, color: '#555', marginTop: 40 }}>
        <div style={{ borderTop: '1px solid #111827', paddingTop: 4, width: 160, textAlign: 'center' }}>
          Received By
        </div>
        <div style={{ borderTop: '1px solid #111827', paddingTop: 4, width: 160, textAlign: 'center' }}>
          Authorised Signatory
        </div>
      </div>

      <div
        style={{
          marginTop: 24,
          fontSize: 9,
          color: '#555',
          textAlign: 'center',
          borderTop: '1px solid #e5e7eb',
          paddingTop: 8,
        }}
      >
        Generated by {generatedBy} on {new Date().toLocaleString('en-PK')} · Computer-generated receipt.
      </div>
    </div>
  );
}
