// PDF Generator for Reports - uses jsPDF (dynamic import)

export interface ReportData {
  companyName: string;
  reportTitle: string;
  dateRange: string;
  summary: { label: string; value: string; color?: string }[];
  records: { columns: string[]; rows: string[][] };
  generatedBy: string;
  generatedAt: string;
}

export async function generateReportPDF(data: ReportData): Promise<Blob> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  let yPos = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(data.companyName, pageWidth / 2, yPos, { align: 'center' });
  yPos += 10;

  doc.setFontSize(14);
  doc.text(data.reportTitle, pageWidth / 2, yPos, { align: 'center' });
  yPos += 7;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(data.dateRange, pageWidth / 2, yPos, { align: 'center' });
  yPos += 12;

  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('Summary', margin, yPos);
  yPos += 8;

  data.summary.forEach((item) => {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 80, 80);
    doc.text(item.label + ':', margin, yPos);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text(item.value, margin + 40, yPos);
    yPos += 6;
  });

  yPos += 8;
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Records', margin, yPos);
  yPos += 8;

  doc.setFillColor(240, 240, 240);
  doc.rect(margin, yPos - 5, contentWidth, 8, 'F');
  doc.setFontSize(9);
  const colWidth = contentWidth / data.records.columns.length;
  data.records.columns.forEach((col, index) => {
    doc.text(col, margin + colWidth * index + 2, yPos);
  });
  yPos += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  data.records.rows.forEach((row, rowIndex) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
      doc.setFillColor(240, 240, 240);
      doc.rect(margin, yPos - 5, contentWidth, 8, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      data.records.columns.forEach((col, index) => {
        doc.text(col, margin + colWidth * index + 2, yPos);
      });
      yPos += 10;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
    }
    if (rowIndex % 2 === 0) {
      doc.setFillColor(250, 250, 250);
      doc.rect(margin, yPos - 4, contentWidth, 7, 'F');
    }
    row.forEach((cell, index) => {
      const text = cell.length > 20 ? cell.substring(0, 17) + '...' : cell;
      doc.text(text, margin + colWidth * index + 2, yPos);
    });
    yPos += 7;
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by: ${data.generatedBy}`, margin, 285);
    doc.text(`Date: ${data.generatedAt}`, margin, 290);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin - 20, 290);
  }

  return doc.output('blob');
}

export function downloadPDF(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

export function printPDF(blob: Blob) {
  const url = URL.createObjectURL(blob);
  const iframe = document.createElement('iframe');
  iframe.style.display = 'none';
  iframe.src = url;
  document.body.appendChild(iframe);
  iframe.onload = () => {
    iframe.contentWindow?.print();
    setTimeout(() => {
      document.body.removeChild(iframe);
      URL.revokeObjectURL(url);
    }, 1000);
  };
}

export async function sharePDF(blob: Blob, filename: string, title: string): Promise<boolean> {
  const file = new File([blob], filename, { type: 'application/pdf' });
  if (navigator.share && navigator.canShare?.({ files: [file] })) {
    try {
      await navigator.share({ title, text: `Sharing ${title}`, files: [file] });
      return true;
    } catch {
      downloadPDF(blob, filename);
      return false;
    }
  }
  downloadPDF(blob, filename);
  return false;
}

// ---------------------------------------------------------------------------
// Specialized generators used by the redesigned reports suite
// ---------------------------------------------------------------------------

const REPORT_HEADER_DEEP = { r: 12, g: 30, b: 54 } as const;
const REPORT_TEXT_MUTED = { r: 100, g: 100, b: 100 } as const;

function fmtAmount(n: number): string {
  const sign = n < 0 ? '-' : '';
  return sign + Math.abs(n).toLocaleString('en-PK', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function drawHeader(doc: any, pageWidth: number, margin: number, companyName: string, title: string, subtitle: string): number {
  doc.setFillColor(REPORT_HEADER_DEEP.r, REPORT_HEADER_DEEP.g, REPORT_HEADER_DEEP.b);
  doc.rect(0, 0, pageWidth, 32, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text(companyName, margin, 13);
  doc.setFontSize(12);
  doc.text(title, margin, 22);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text(subtitle, margin, 28);
  doc.setTextColor(0, 0, 0);
  return 42;
}

function drawFooter(doc: any, pageWidth: number, margin: number, generatedBy: string, generatedAt: string): void {
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(REPORT_TEXT_MUTED.r, REPORT_TEXT_MUTED.g, REPORT_TEXT_MUTED.b);
    doc.text(`Generated by: ${generatedBy}`, margin, 285);
    doc.text(`Date: ${generatedAt}`, margin, 290);
    doc.text(`Page ${i} of ${total}`, pageWidth - margin - 20, 290);
  }
}

export interface LedgerPdfRow {
  date: string;
  reference: string;
  description: string;
  debit: number;
  credit: number;
  balance: number;
}

export interface LedgerPdfOptions {
  companyName: string;
  title: string;
  subtitle: string;
  partyName: string;
  partyMeta?: string;
  openingBalance: number;
  closingBalance: number;
  totals: { debit: number; credit: number };
  rows: LedgerPdfRow[];
  generatedBy: string;
  generatedAt: string;
}

export async function generateLedgerPDF(opts: LedgerPdfOptions): Promise<Blob> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const content = pageWidth - margin * 2;

  let y = drawHeader(doc, pageWidth, margin, opts.companyName, opts.title, opts.subtitle);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(opts.partyName, margin, y);
  y += 5;
  if (opts.partyMeta) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(REPORT_TEXT_MUTED.r, REPORT_TEXT_MUTED.g, REPORT_TEXT_MUTED.b);
    doc.text(opts.partyMeta, margin, y);
    y += 4;
  }
  doc.setTextColor(0, 0, 0);
  y += 4;

  const summary = [
    { label: 'Opening balance', value: fmtAmount(opts.openingBalance) },
    { label: 'Total debit', value: fmtAmount(opts.totals.debit) },
    { label: 'Total credit', value: fmtAmount(opts.totals.credit) },
    { label: 'Closing balance', value: fmtAmount(opts.closingBalance) },
  ];
  const cellW = content / summary.length;
  summary.forEach((s, i) => {
    doc.setFillColor(247, 248, 252);
    doc.rect(margin + cellW * i, y, cellW - 2, 14, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(REPORT_TEXT_MUTED.r, REPORT_TEXT_MUTED.g, REPORT_TEXT_MUTED.b);
    doc.text(s.label, margin + cellW * i + 2, y + 5);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(s.value, margin + cellW * i + 2, y + 11);
  });
  y += 20;

  const cols: { key: keyof LedgerPdfRow; label: string; width: number; align?: 'right' }[] = [
    { key: 'date', label: 'Date', width: 22 },
    { key: 'reference', label: 'Ref #', width: 26 },
    { key: 'description', label: 'Description', width: content - 22 - 26 - 26 - 26 - 26 },
    { key: 'debit', label: 'Debit', width: 26, align: 'right' },
    { key: 'credit', label: 'Credit', width: 26, align: 'right' },
    { key: 'balance', label: 'Balance', width: 26, align: 'right' },
  ];

  const drawTableHeader = (yStart: number): number => {
    doc.setFillColor(REPORT_HEADER_DEEP.r, REPORT_HEADER_DEEP.g, REPORT_HEADER_DEEP.b);
    doc.rect(margin, yStart, content, 7, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    let x = margin + 2;
    cols.forEach((c) => {
      if (c.align === 'right') {
        doc.text(c.label, x + c.width - 4, yStart + 5, { align: 'right' });
      } else {
        doc.text(c.label, x, yStart + 5);
      }
      x += c.width;
    });
    doc.setTextColor(0, 0, 0);
    return yStart + 9;
  };

  y = drawTableHeader(y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);

  opts.rows.forEach((row, idx) => {
    if (y > 270) {
      doc.addPage();
      y = drawHeader(doc, pageWidth, margin, opts.companyName, opts.title, opts.subtitle);
      y = drawTableHeader(y);
    }
    if (idx % 2 === 0) {
      doc.setFillColor(250, 251, 253);
      doc.rect(margin, y - 4, content, 6, 'F');
    }
    let x = margin + 2;
    cols.forEach((c) => {
      const raw = row[c.key];
      const text = typeof raw === 'number' ? fmtAmount(raw) : String(raw ?? '—');
      const clip = text.length > 60 ? text.slice(0, 57) + '…' : text;
      if (c.align === 'right') {
        doc.text(clip, x + c.width - 4, y, { align: 'right' });
      } else {
        doc.text(clip, x, y);
      }
      x += c.width;
    });
    y += 6;
  });

  drawFooter(doc, pageWidth, margin, opts.generatedBy, opts.generatedAt);
  return doc.output('blob');
}

export interface TimelinePdfGroup {
  date: string;
  rows: {
    time: string;
    party: string;
    reference: string;
    fromAccount?: string;
    toAccount?: string;
    amount: number;
    direction: 'in' | 'out';
  }[];
}

export interface TimelinePdfOptions {
  companyName: string;
  title: string;
  subtitle: string;
  totals: { inAmount: number; outAmount: number; net: number; count: number };
  groups: TimelinePdfGroup[];
  generatedBy: string;
  generatedAt: string;
}

export async function generateTimelinePDF(opts: TimelinePdfOptions): Promise<Blob> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const content = pageWidth - margin * 2;

  let y = drawHeader(doc, pageWidth, margin, opts.companyName, opts.title, opts.subtitle);

  const summary = [
    { label: 'Received', value: fmtAmount(opts.totals.inAmount) },
    { label: 'Paid', value: fmtAmount(opts.totals.outAmount) },
    { label: 'Net', value: fmtAmount(opts.totals.net) },
    { label: 'Count', value: String(opts.totals.count) },
  ];
  const cellW = content / summary.length;
  summary.forEach((s, i) => {
    doc.setFillColor(247, 248, 252);
    doc.rect(margin + cellW * i, y, cellW - 2, 14, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(REPORT_TEXT_MUTED.r, REPORT_TEXT_MUTED.g, REPORT_TEXT_MUTED.b);
    doc.text(s.label, margin + cellW * i + 2, y + 5);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(s.value, margin + cellW * i + 2, y + 11);
  });
  y += 20;

  for (const group of opts.groups) {
    if (y > 260) {
      doc.addPage();
      y = drawHeader(doc, pageWidth, margin, opts.companyName, opts.title, opts.subtitle);
    }
    doc.setFillColor(237, 240, 248);
    doc.rect(margin, y, content, 7, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);
    doc.text(group.date, margin + 2, y + 5);
    y += 10;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    for (const r of group.rows) {
      if (y > 275) {
        doc.addPage();
        y = drawHeader(doc, pageWidth, margin, opts.companyName, opts.title, opts.subtitle);
      }
      const isIn = r.direction === 'in';
      doc.setTextColor(isIn ? 22 : 185, isIn ? 128 : 28, isIn ? 75 : 28);
      doc.text(isIn ? 'IN' : 'OUT', margin + 2, y);
      doc.setTextColor(0, 0, 0);
      const line = `${r.time}  ${r.party}  ·  ${r.reference}`;
      const clipped = line.length > 78 ? line.slice(0, 75) + '…' : line;
      doc.text(clipped, margin + 12, y);
      doc.setFont('helvetica', 'bold');
      doc.text(fmtAmount(r.amount), margin + content - 2, y, { align: 'right' });
      doc.setFont('helvetica', 'normal');
      y += 4.5;
      if (r.fromAccount || r.toAccount) {
        doc.setTextColor(REPORT_TEXT_MUTED.r, REPORT_TEXT_MUTED.g, REPORT_TEXT_MUTED.b);
        doc.setFontSize(7);
        const route = [r.fromAccount && `From: ${r.fromAccount}`, r.toAccount && `To: ${r.toAccount}`]
          .filter(Boolean)
          .join('   ');
        const clipRoute = route.length > 100 ? route.slice(0, 97) + '…' : route;
        doc.text(clipRoute, margin + 12, y);
        doc.setFontSize(8);
        doc.setTextColor(0, 0, 0);
        y += 4;
      }
      y += 1;
    }
    y += 3;
  }

  drawFooter(doc, pageWidth, margin, opts.generatedBy, opts.generatedAt);
  return doc.output('blob');
}

export interface AgingPdfBucket {
  label: string;
  count: number;
  amount: number;
}

export interface AgingPdfParty {
  name: string;
  meta?: string;
  buckets: number[];
  total: number;
}

export interface AgingPdfOptions {
  companyName: string;
  title: string;
  subtitle: string;
  bucketLabels: string[];
  totals: AgingPdfBucket[];
  grandTotal: number;
  parties: AgingPdfParty[];
  generatedBy: string;
  generatedAt: string;
}

export async function generateAgingPDF(opts: AgingPdfOptions): Promise<Blob> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  const content = pageWidth - margin * 2;

  let y = drawHeader(doc, pageWidth, margin, opts.companyName, opts.title, opts.subtitle);

  // Bucket totals
  const cellW = content / opts.totals.length;
  opts.totals.forEach((b, i) => {
    doc.setFillColor(247, 248, 252);
    doc.rect(margin + cellW * i, y, cellW - 2, 16, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(REPORT_TEXT_MUTED.r, REPORT_TEXT_MUTED.g, REPORT_TEXT_MUTED.b);
    doc.text(b.label, margin + cellW * i + 2, y + 5);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(fmtAmount(b.amount), margin + cellW * i + 2, y + 11);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(REPORT_TEXT_MUTED.r, REPORT_TEXT_MUTED.g, REPORT_TEXT_MUTED.b);
    doc.text(`${b.count} item${b.count === 1 ? '' : 's'}`, margin + cellW * i + 2, y + 15);
  });
  doc.setTextColor(0, 0, 0);
  y += 22;

  const partyCol = 70;
  const bucketW = (content - partyCol - 30) / opts.bucketLabels.length;

  const drawAgingTableHeader = (yStart: number): number => {
    doc.setFillColor(REPORT_HEADER_DEEP.r, REPORT_HEADER_DEEP.g, REPORT_HEADER_DEEP.b);
    doc.rect(margin, yStart, content, 7, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8.5);
    doc.text('Party', margin + 2, yStart + 5);
    opts.bucketLabels.forEach((l, i) => {
      doc.text(l, margin + partyCol + bucketW * i + bucketW - 2, yStart + 5, { align: 'right' });
    });
    doc.text('Total', margin + content - 2, yStart + 5, { align: 'right' });
    doc.setTextColor(0, 0, 0);
    return yStart + 9;
  };

  y = drawAgingTableHeader(y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);

  opts.parties.forEach((p, idx) => {
    if (y > 190) {
      doc.addPage();
      y = drawHeader(doc, pageWidth, margin, opts.companyName, opts.title, opts.subtitle);
      y = drawAgingTableHeader(y);
    }
    if (idx % 2 === 0) {
      doc.setFillColor(250, 251, 253);
      doc.rect(margin, y - 4, content, 6, 'F');
    }
    const label = p.meta ? `${p.name}  ·  ${p.meta}` : p.name;
    doc.text(label.length > 40 ? label.slice(0, 37) + '…' : label, margin + 2, y);
    p.buckets.forEach((v, i) => {
      doc.text(fmtAmount(v), margin + partyCol + bucketW * i + bucketW - 2, y, { align: 'right' });
    });
    doc.setFont('helvetica', 'bold');
    doc.text(fmtAmount(p.total), margin + content - 2, y, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    y += 6;
  });

  y += 2;
  doc.setFillColor(REPORT_HEADER_DEEP.r, REPORT_HEADER_DEEP.g, REPORT_HEADER_DEEP.b);
  doc.rect(margin, y, content, 7, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.text('Grand total', margin + 2, y + 5);
  doc.text(fmtAmount(opts.grandTotal), margin + content - 2, y + 5, { align: 'right' });
  doc.setTextColor(0, 0, 0);

  drawFooter(doc, pageWidth, margin, opts.generatedBy, opts.generatedAt);
  return doc.output('blob');
}

/**
 * Convenience: share a PDF blob via navigator.share (files) with download and
 * a WhatsApp-link fallback when the user wants to forward it directly.
 */
export async function shareReportBlob(
  blob: Blob,
  filename: string,
  title: string,
  whatsAppText?: string,
): Promise<void> {
  const ok = await sharePDF(blob, filename, title);
  if (!ok && whatsAppText) {
    const url = `https://wa.me/?text=${encodeURIComponent(whatsAppText)}`;
    window.open(url, '_blank', 'noopener,noreferrer');
  }
}
