# Sync Supabase URL and anon key from project root to erp-mobile-app/.env
# Run from project root: .\scripts\sync-mobile-env.ps1
# So mobile app (localhost:5174) uses same backend as web.

$ErrorActionPreference = 'Stop'
$root = (Get-Item $PSScriptRoot).Parent.FullName
$envRoot = Join-Path $root '.env'
$envProd = Join-Path $root '.env.production'
$mobileEnv = Join-Path $root 'erp-mobile-app\.env'
$mobileDir = Split-Path $mobileEnv -Parent

$url = ''
$key = ''
foreach ($path in $envProd, $envRoot) {
    if (-not (Test-Path $path)) { continue }
    Get-Content $path | ForEach-Object {
        if ($_ -match '^\s*VITE_SUPABASE_URL=(.+)$') { $url = $Matches[1].Trim().Trim('"') }
        if ($_ -match '^\s*VITE_SUPABASE_ANON_KEY=(.+)$') { $key = $Matches[1].Trim().Trim('"') }
    }
    if ($url -and $key) { break }
}

if (-not $url) { $url = 'https://supabase.dincouture.pk' }
if (-not $key) {
    Write-Host 'WARN: VITE_SUPABASE_ANON_KEY not found in .env or .env.production. Add it to erp-mobile-app\.env manually (same as web app).' -ForegroundColor Yellow
}

if (-not (Test-Path $mobileDir)) { New-Item -ItemType Directory -Path $mobileDir -Force | Out-Null }
@"
# Auto-generated by scripts/sync-mobile-env.ps1 - same backend as web app
VITE_SUPABASE_URL=$url
VITE_SUPABASE_ANON_KEY=$key
"@ | Set-Content -Path $mobileEnv -Encoding utf8
Write-Host "Wrote $mobileEnv (VITE_SUPABASE_URL=$url). Restart mobile dev server: cd erp-mobile-app && npm run dev"
exit 0
