#!/bin/bash
# Copy VPS Supabase anon JWT into project-root .env.local for local Vite dev.
# Usage: bash scripts/sync-local-env-from-vps.sh
set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$ROOT/.env.local"
SSH_HOST="${SSH_HOST:-dincouture-vps}"
SUPABASE_ENV="${SUPABASE_ENV:-/root/supabase/docker/.env}"

echo "[sync-local-env] Reading ANON_KEY from $SSH_HOST:$SUPABASE_ENV ..."
RAW=$(ssh "$SSH_HOST" "grep '^ANON_KEY=' '$SUPABASE_ENV' 2>/dev/null | cut -d= -f2- | tr -d '\n\r'") || true
if [ -z "$RAW" ]; then
  RAW=$(ssh "$SSH_HOST" "grep '^SUPABASE_ANON_KEY=' '$SUPABASE_ENV' 2>/dev/null | cut -d= -f2- | tr -d '\n\r'") || true
fi
if [ -z "$RAW" ]; then
  echo "[sync-local-env] ERROR: Could not read ANON_KEY from $SUPABASE_ENV on $SSH_HOST"
  exit 1
fi

LEN=${#RAW}
echo "[sync-local-env] Anon key length: $LEN"
if [ "$LEN" -lt 100 ]; then
  echo "[sync-local-env] WARN: anon key looks too short"
fi

cat > "$OUT" <<EOF
# Auto-generated by scripts/sync-local-env-from-vps.sh — do not commit
VITE_SUPABASE_URL=https://supabase.dincouture.pk
VITE_SUPABASE_ANON_KEY=$RAW
EOF

echo "[sync-local-env] Wrote $OUT"
echo "[sync-local-env] Restart: npm run dev"
